import mongoose from "mongoose";

const shoesSchema = new mongoose.Schema({
  shoesName: { type: String, required: true },
  imageUrl: { type: String },
  price: { type: Number, required: true },
  deadlineStatus: { type: Number, default: 0 },
  retailer: {
    type: mongoose.Schema.Types.ObjectId,
    required: true,
    ref: "Retailer",
  },
  size: {
    m_240: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_245: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_250: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_255: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_260: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_265: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_270: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_275: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_280: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_285: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_290: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_295: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_300: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_305: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
    m_310: {
      stocks: { type: Number, default: 0 },
      applicants: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
      winner: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
    },
  },
  // sizeStocks: {
  //   m_240: { type: Number, default: 0 },
  //   m_245: { type: Number, default: 0 },
  //   m_250: { type: Number, default: 0 },
  //   m_255: { type: Number, default: 0 },
  //   m_260: { type: Number, default: 0 },
  //   m_265: { type: Number, default: 0 },
  //   m_270: { type: Number, default: 0 },
  //   m_275: { type: Number, default: 0 },
  //   m_280: { type: Number, default: 0 },
  //   m_285: { type: Number, default: 0 },
  //   m_290: { type: Number, default: 0 },
  //   m_295: { type: Number, default: 0 },
  //   m_300: { type: Number, default: 0 },
  //   m_305: { type: Number, default: 0 },
  //   m_310: { type: Number, default: 0 },
  // },
  // applicants: {
  //   m_240: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_245: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_250: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_255: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_260: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_265: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_270: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_275: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_280: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_285: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_290: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_295: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_300: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_305: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_310: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  // },
  // winner: {
  //   m_240: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_245: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_250: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_255: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_260: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_265: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_270: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_275: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_280: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_285: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_290: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_295: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_300: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_305: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  //   m_310: [{ type: mongoose.Schema.Types.ObjectId, ref: "User" }],
  // },
});

const Shoes = mongoose.model("Shoes", shoesSchema);

export default Shoes;
